spring:
  application:
    name: auth-logs-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/inspector}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${PORT:8080}

app:
  jwt:
    # base64-encoded 256-bit key. Replace in prod.
    secret: ${JWT_SECRET:ZmFrZV9qd3Rfc2VjcmV0X2NoYW5nZW1lX2NoYW5nZW1lXzMyX2J5dGVz}
    ttl-seconds: ${JWT_TTL_SECONDS:28800} # 8 hours

management:
  endpoints:
    web:
      exposure:
        include: health,info
