spring:
  application:
    name: realtime-maps-backend

  datasource:
    url: jdbc:h2:mem:inspectordb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

server:
  port: 8080

logging:
  level:
    com.myki.inspector: DEBUG

# Google Maps API configuration
google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY:}
    browser-api-key: ${GOOGLE_MAPS_BROWSER_API_KEY:${GOOGLE_MAPS_API_KEY:}}
